name: spectronV2
main: TheWindows\spectron\Loader
api: 5.0.0
authors:
  - TheWindows
  - pmCraftiR
description: "ReCreated By TheWindows"
version: 2.0.1

permissions:
  spectron.command.spectron:
    description: "Control fake player"
    default: op